config-version: 2

name: 'jaffle_shop'
version: '1.0.0'
profile: 'jaffle_shop'
config-version: 2

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

on-run-end: "grant select on all tables in schema {{ target.schema }} group transformer"

seeds:
  +schema: raw

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
